# application.yml
#spring
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: jhPage
    password: jhPage
  mail:
    host: smtp.gmail.com
    port: 587
    username: k0j4h25@gmail.com
    password: wjvemhrwgckrtgli
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 1800000

#logback
logging:
  level:
    root: info
    '[com.jhproject]': debug

#mybatis
mybatis:
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  type-aliases-package: com.jhProject.app, org.springframework.security.core.authority
  mapper-locations: classpath*:mapper/**/*-mapper.xml
  
# jwt configuration
jwt:
  secret-key: 3A7F91B2E4D6F8A5C7B9D1F33A7F91B2E4D6F8A5C7B9D1F33A7F91B2E4D6F8A5C7B9D1F33A7F91B2E4D6F8A5C7B9D1F33A7F91B2E4D6F8A5C7B9D1F3